import type { AppState, Project, AppStore } from "./types";

export const initialState: AppState = {
  members: [
    { id: "m1", name: "Alex Martin", role: "po" },
    { id: "m2", name: "Sarah Dubois", role: "sm" },
    { id: "m3", name: "Thomas Bernard", role: "dev" },
    { id: "m4", name: "Emma Petit", role: "dev" },
    { id: "m5", name: "Lucas Moreau", role: "tester" },
    { id: "m6", name: "Chloé Roux", role: "designer" },
  ],
  sprints: [
    {
      id: "s1",
      name: "Sprint 1",
      goal: "Créer la landing page et l'authentification",
      startDate: "2026-01-06",
      endDate: "2026-01-19",
      status: "completed",
      storyIds: ["st1", "st2", "st3"],
    },
    {
      id: "s2",
      name: "Sprint 2",
      goal: "Développer le tableau Kanban et la gestion des tâches",
      startDate: "2026-01-20",
      endDate: "2026-02-02",
      status: "active",
      storyIds: ["st4", "st5", "st6", "st7"],
    },
    {
      id: "s3",
      name: "Sprint 3",
      goal: "Intégrer les statistiques et rapports",
      startDate: "2026-02-03",
      endDate: "2026-02-16",
      status: "planned",
      storyIds: [],
    },
  ],
  stories: [
    {
      id: "st1",
      title: "En tant que visiteur, je veux voir une landing page",
      description: "Créer une page d'accueil attractive présentant le produit.",
      status: "done",
      priority: "high",
      points: 5,
      assigneeId: "m6",
      sprintId: "s1",
      createdAt: "2026-01-05",
    },
    {
      id: "st2",
      title: "En tant qu'utilisateur, je veux créer un compte",
      description: "Formulaire d'inscription avec email et mot de passe.",
      status: "done",
      priority: "critical",
      points: 8,
      assigneeId: "m3",
      sprintId: "s1",
      createdAt: "2026-01-05",
    },
    {
      id: "st3",
      title: "En tant qu'utilisateur, je veux me connecter",
      description: "Page de connexion sécurisée avec JWT.",
      status: "done",
      priority: "critical",
      points: 8,
      assigneeId: "m4",
      sprintId: "s1",
      createdAt: "2026-01-05",
    },
    {
      id: "st4",
      title: "En tant que PO, je veux créer des user stories",
      description: "Formulaire de création de stories avec titre, description et points.",
      status: "in-progress",
      priority: "critical",
      points: 8,
      assigneeId: "m3",
      sprintId: "s2",
      createdAt: "2026-01-18",
    },
    {
      id: "st5",
      title: "En tant qu'équipe, nous voulons un tableau Kanban",
      description: "Tableau avec colonnes personnalisables et glisser-déposer.",
      status: "todo",
      priority: "high",
      points: 13,
      assigneeId: "m4",
      sprintId: "s2",
      createdAt: "2026-01-18",
    },
    {
      id: "st6",
      title: "En tant que SM, je veux planifier des sprints",
      description: "Création de sprints avec objectifs, dates et sélection de stories.",
      status: "todo",
      priority: "high",
      points: 8,
      assigneeId: "m2",
      sprintId: "s2",
      createdAt: "2026-01-18",
    },
    {
      id: "st7",
      title: "En tant qu'équipe, nous voulons un burndown chart",
      description: "Graphique d'avancement du sprint.",
      status: "backlog",
      priority: "medium",
      points: 5,
      assigneeId: "m5",
      sprintId: "s2",
      createdAt: "2026-01-18",
    },
    {
      id: "st8",
      title: "En tant qu'utilisateur, je veux recevoir des notifications",
      description: "Système de notifications en temps réel.",
      status: "backlog",
      priority: "low",
      points: 3,
      sprintId: undefined,
      createdAt: "2026-01-25",
    },
    {
      id: "st9",
      title: "En tant qu'admin, je veux gérer les membres",
      description: "Interface de gestion des rôles et permissions.",
      status: "backlog",
      priority: "medium",
      points: 5,
      sprintId: undefined,
      createdAt: "2026-01-25",
    },
  ],
  activeSprintId: "s2",
};

export const defaultProject: Project = {
  id: "proj-default",
  name: "Projet Exemple",
  color: "from-indigo-500 to-violet-600",
  description: "Projet de démonstration avec des données d'exemple.",
  createdAt: "2026-01-01",
  state: initialState,
};

export const initialStore: AppStore = {
  projects: [defaultProject],
  activeProjectId: "proj-default",
  version: 1,
};
